<<1>> Intriguojantis scenarijus patestavimui:

> the existing load balancing designs are agnostic to the heterogeneous datacenter traffic, i.e., a mass of delay-sensitive short flows mix with a handful of throughput-oriented long flows, and casually reroute these flows regardless of path condition, thus resulting in frequent flow collisions. The short flows suffer from the problem of large queuing delay due to colliding with long flows, while the frequent collisions between long flows lead to low network utilization and serious throughput degradation.
> 
> To address these inefficiencies, we propose an isolation-based load balancing scheme, namely ILB, which perceives flow collisions and dynamically isolates the long flows from short flows.
> Specifically, when a long flow collides with short flows in the same path, it immediately switches to another path unused by short flows to help the short ones in the previous path complete quickly.

{nbsp}  +

<<2>> Skeduleriai patestavimui:

> We also compared four schedulers of MPTCP that are implemented in Linux Kernel.
> Results showed that difference in round trip times of sub-paths affects MPTCP performance. 

{nbsp}  +

<<3>> Kitas intriguojantis scenarijus testavimui ir išmatavimui:

> With the wide application of multi host hosts, in the FatTree topology, 
> a performance bottleneck exists that causes throughput collapse in the Incast communication pattern leading to the collapse and seriously affects the network energy.
> In this paper, based on the queuing network and the Markov property of the MPTCP scheduling process, 
> we propose a multilevel cooperative MPTCP Incast performance evaluation model whose levels are called M/M/N/m1 M/M/L/m2 M/M/K/m3 
> to study the delay performance in MPTCP Incast throughput collapse.

=== Šaltiniai

`2022-02` **[[[1]]]** `sciencedirect.com`: _Tao Zhang_ et al., https://doi.org/10.1016/j.future.2021.09.002[Load balancing with traffic isolation in data center networks]

`2021-12` **[[[2]]]** `springer.com`: Vidya S. Kubde, et al., https://doi.org/10.1007/978-981-16-4369-9_9[Analysis of Multipath TCP Schedulers]

`2021-11` **[[[3]]]** `ieee.org`: Jiamin Yao, et al., https://doi.org/10.1109/TGCN.2021.3125860[Performance Evaluation of MPTCP Incast Based on Queuing Network]
